FORMAT: 1A

# Spotters

# Group Missions 
Missions

## Missions Collection [/missions{?location}]
### List 40 closest Missions [GET]
+ Parameters
    + location (required, array, `40.714728,-73.998672`) ... Location whre to look for missions
    
+ Response 200 (application/json)

        [
            {
              "id": 1, 
              "title": "Nice and easy", 
              "company": "Tesco",
              "address": {
                "coordinates": [40.714728, -73.998672],
                "distance": "0.2km"
              }, 
              "dueDate": "30-12-2014 22:10", 
              "price": 5
            },
            {
              "id": 2, 
              "title": "Nice and easy", 
              "company": "Tesco",
              "address": {
                "coordinates": [40.714728, -74.998672],
                "distance": "10.2km"
              }, 
              "dueDate": "31-12-2014 12:10", 
              "price": 10
            }
        ]

## Mission Details [/missions/{id}]
A single Mission object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Mission [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                  "id": 1,
                  "title": "Nice and easy",
                  "company": "Tesco",
                  "address": {
                    "coordinates": [40.714728, -73.998672],
                    "distance": "0.2km"
                  },
                  "status": "open",
                  "dueDate": "2015-01-22T15:20:38",
                  "price": 5,
                  "tasks": [
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "photo", "count": 1, "icon": "ion-help-circled"}
                  ],
                  "instructions": "<p>Some <b>html</b> descipiton</p>"
            }
            
## Accept Mission [/missions/{id}/accept]

### Accept a mission [PUT]
+ Response 200 (application/json)

    + Body
    
            {
                  "id": 1,
                  "title": "Nice and easy",
                  "company": "Tesco",
                  "address": {
                    "coordinates": [40.714728, -73.998672],
                    "distance": "0.2km"
                  },
                  "dueDate": "2015-01-22T15:20:38",
                  "bookingDueTime": "",
                  "status": "booked",
                  "price": 5,
                  "tasks": [
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "photo", "count": 1, "icon": "ion-help-circled"}
                  ],
                  "instructions": "<p>Some <b>html</b> descipiton</p>"
            }
            
### Decline a mission [DELETE]

+ Response 200 (application/json)

    + Body
    
            {
                  "id": 1,
                  "title": "Nice and easy",
                  "company": "Tesco",
                  "address": {
                    "coordinates": [40.714728, -73.998672],
                    "distance": "0.2km"
                  },
                  "dueDate": "2015-01-22T15:20:38",
                  "bookingDueTime": "2015-01-10T15:20:38"
                  "status": "open",
                  "price": 5,
                  "tasks": [
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "question", "count": 5, "icon": "ion-alert"},
                    {"type": "photo", "count": 1, "icon": "ion-help-circled"}
                  ],
                  "instructions": "<p>Some <b>html</b> descipiton</p>"
            }
